version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 81:2368
    environment:
      url: ${URL}
      volumes:
        - '~/data/ghost_data:/var/lib/ghost/content'

