version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 80:2368
    environment:
      url: '${URL}'
    volumes:
      - 'ghost_data:/var/lib/ghost/content'

volumes:
  ghost_data:
