version: '3.7'

services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v2.2'
    restart: always
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --api.insecure=false
      - --certificatesresolvers.mytlschallenge.acme.email=${EMAIL}
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.docker=true
      - --providers.file.filename=/dynamic.yaml
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - './dynamic.yaml:/dynamic.yaml'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`${DASHBOARD_HOST}`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.api.tls=true'

  whoami:
    container_name: 'simple-service'
    image: 'containous/whoami'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.entrypoints=web'
      - 'traefik.http.routers.whoami.middlewares=redirect@file'
      - 'traefik.http.routers.whoami.rule=(Host(`${WHOAMI_HOST}`) || Host(`www.${WHOAMI_HOST}`))'
      - 'traefik.http.routers.whoamisecure.entrypoints=websecure'
      - 'traefik.http.routers.whoamisecure.rule=(Host(`${WHOAMI_HOST}`) || Host(`www.${WHOAMI_HOST}`))'
      - 'traefik.http.routers.whoamisecure.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.whoamisecure.tls=true'
    networks:
      - web

networks:
  web:
    external: true
  # backend:
  #   external: false
