version: "3.7"

services:
  traefik:
    image: "traefik:v2.2"
    restart: always
    container_name: "traefik"
    command:
      # - --certificatesresolvers.mytlschallenge.acme.email=you@youremail
      # - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --api.dashboard=true
      - --api.debug=true
      - --api.insecure=false
      - --entrypoints.web-secured.address=:443
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.docker=true
      - --providers.file.filename=/dynamic.yaml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - #- ./letsencrypt:/letsencrypt
      - ./dynamic.yaml:/dynamic.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`status.dadamix.com`)"
      - "traefik.http.routers.api.service=api@internal"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=(Host(`dadamix.com`) || Host(`www.dadamix.com`))"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - web

networks:
  web:
    external: true
  backend:
    external: false
