version: '3.7'

services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v2.2'
    restart: always
    command:
      - --api.dashboard=true
      - --api.debug=false
      - --api.insecure=false
      - --certificatesresolvers.mytlschallenge.acme.email=${EMAIL}
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --entrypoints.web.address=:${WEB_PORT}
      - --entrypoints.websecure.address=:${WEBSECURE_PORT}
      - --log.level=ERROR # DEBUG, PANIC, FATAL, ERROR, WARN, INFO
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.docker=true
      - --providers.file.filename=/dynamic.yaml
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - './dynamic.yaml:/dynamic.yaml'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`status.${HOST}`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.api.tls=true'

  whoami:
    container_name: 'simple-service'
    image: 'containous/whoami'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.entrypoints=web'
      - 'traefik.http.routers.whoami.middlewares=redirect@file'
      - 'traefik.http.routers.whoami.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
      - 'traefik.http.routers.whoamisecure.entrypoints=websecure'
      - 'traefik.http.routers.whoamisecure.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
      - 'traefik.http.routers.whoamisecure.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.whoamisecure.tls=true'
    networks:
      - web

  miniflux:
    container_name: 'miniflux'
    image: 'miniflux/miniflux'
    restart: always
    depends_on:
      - pg
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg/miniflux?sslmode=disable
      - POLLING_FREQUENCY=10
      - RUN_MIGRATIONS=${MINIFLUX_INIT}
      - CREATE_ADMIN=${MINIFLUX_INIT}
      - ADMIN_USERNAME=${MINIFLUX_ADMIN}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASSWORD}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.miniflux.entrypoints=websecure'
      - 'traefik.http.routers.miniflux.middlewares=redirect@file'
      - 'traefik.http.routers.miniflux.rule=Host(`rss.${HOST}`)'
      - 'traefik.http.routers.miniflux.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.miniflux.tls=true'
    networks:
      - web
      - backend

  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: always
    depends_on:
      - pg
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - SYMFONY__ENV__SECRET=${WALLABAG_ENV_SECRET}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_DRIVER_CLASS=Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
      - SYMFONY__ENV__DATABASE_HOST=pg
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=${WALLABAG_DB_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASSWORD}
      - SYMFONY__ENV__DOMAIN_NAME=https://later.${HOST}
    volumes:
      - ./data/wallabag_images:/var/www/wallabag/web/assets/images
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wallabag.entrypoints=websecure'
      - 'traefik.http.routers.wallabag.middlewares=redirect@file'
      - 'traefik.http.routers.wallabag.rule=Host(`later.${HOST}`)'
      - 'traefik.http.routers.wallabag.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.wallabag.tls=true'
    networks:
      - backend
      - web

  pg:
    container_name: 'postrgres'
    image: 'postgres:12-alpine'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
      # - './data/postgres/:/var/lib/postgresql/data'
    networks:
      - backend

  pgbackups:
    container_name: 'pgbackups'
    image: 'prodrigestivill/postgres-backup-local:12-alpine'
    restart: always
    volumes:
      - './data/pg_backups:/backups'
    links:
      - pg
    depends_on:
      - pg
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_DB=${POSTGRES_DB},wallabag,miniflux
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
    networks:
      - backend

volumes:
  pg_data:
  wallabag_images:

networks:
  web:
    external: true
  backend:
    external: false
