version: '3.7'

services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
      - webproxy
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.helloworld.entrypoints=web'
        - 'traefik.http.routers.helloworld.rule=Host(`helloworld.${HOST}`)'
        - 'traefik.http.services.helloworld.loadbalancer.server.port=80'

networks:
  webproxy:
    external: true
