version: '3.7'

services:
  whoami:
    image: 'containous/whoami'
    networks:
      - webproxy
    deploy:
      labels:
        # - 'traefik.http.routers.whoami.tls.certresolver=mytlschallenge'
        - 'traefik.enable=true'
        - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
        - 'traefik.http.routers.whoami.entrypoints=websecure'
        - 'traefik.http.routers.whoami.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
        - 'traefik.http.routers.whoami.tls=true'
        - 'traefik.http.routers.whoamiinsecure.entrypoints=web'
        - 'traefik.http.routers.whoamiinsecure.middlewares=redirect-to-https@docker'
        - 'traefik.http.routers.whoamiinsecure.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
        - 'traefik.http.routers.whoamiinsecure.rule=hostregexp(`{host:.+}`)'
        - 'traefik.http.services.whoami.loadbalancer.server.port=80'

networks:
  webproxy:
    external: true
