version: '3.7'

services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v2.2'
    restart: always
    command:
      - --api.dashboard=true
      - --api.debug=false
      - --api.insecure=false
      - --certificatesresolvers.mytlschallenge.acme.email=${EMAIL}
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --entrypoints.web.address=:${WEB_PORT}
      - --entrypoints.websecure.address=:${WEBSECURE_PORT}
      - --log.level=ERROR # DEBUG, PANIC, FATAL, ERROR, WARN, INFO
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.docker.swarmMode=true
      - --providers.file.filename=/dynamic.yaml
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - './dynamic.yaml:/dynamic.yaml'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`status.${HOST}`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.api.tls=true'

  whoami:
    container_name: 'simple-service'
    image: 'containous/whoami'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.entrypoints=web'
      - 'traefik.http.routers.whoami.middlewares=redirect@file'
      - 'traefik.http.routers.whoami.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
      - 'traefik.http.routers.whoamisecure.entrypoints=websecure'
      - 'traefik.http.routers.whoamisecure.rule=(Host(`${HOST}`) || Host(`www.${HOST}`))'
      - 'traefik.http.routers.whoamisecure.tls.certresolver=mytlschallenge'
      - 'traefik.http.routers.whoamisecure.tls=true'
    networks:
      - web

networks:
  web:
    external: true
  backend:
    external: false
