version: '3.7'

services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
      - webproxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`helloworld.test.local`)"
        - "traefik.http.routers.helloworld.entrypoints=web"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"

networks:
  webproxy:
    external: true
